### ISSUE TITLE
[CZ] Několik poznatků a dotazů

### ISSUE THREAD

**Issue by martinrotter** [michal-h21/biblatex-iso690#10]
Používám iso-numeric, berme v potaz taky ![biblio](https://cloud.githubusercontent.com/assets/1255302/5168131/e6c1705e-73fc-11e4-8870-fda4a5b49102.png) obrázek.
1. Jak docílit toho, aby za číslovkou označuíjcí pořadí záznamu byla tečka? Jak zajistit, aby číslo bylo formátováno například jako [1.]?
2. Jak zajistit, aby první řádek (ten s číslem záznamu) nebyl předsazený?
3. Jak opravit problém v záznamu číslo 1, poslední řádek, kde jsou mezery u textu "60 s. Dostupný..." moc stlačené?

Děkuji za odpovědi.

**Comment by dominikmatus** [comment]
Rád bych navrhl pár změn. Poslední norma zjednodušuje URL odkaz, tedy ostré závorky nejsou potřeba a odkaz nekončí tečkou. Což je problém u knih, které jsou i online. ISBN se vypíše až za odkazem. 
Dále, nějak mi nefunguje iso-authortitle. Kód mi přijde dost podobný u iso-authoryear. 
Je možné tyto věci nějak zapracovat? Díky moc.

**Comment by DavidLuptak** [comment]
@dominikmatus zmeny zapracované.

Suggestions from this issue incorporated, hints how to change some styling put into [wiki style guide](https://github.com/michal-h21/biblatex-iso690/wiki/Style-Guide).

Closing.
