### ISSUE TITLE
Problém s kompilací

### ISSUE THREAD

**Issue by dominikmatus** [michal-h21/biblatex-iso690#11]
Zdravím,
s latexem jsem víceméně začátečník. Mám stále problém s kompilací s biberem, kvůli tomu jsem si musel upravit nedostatečný csplainnat, protože jsem to vzdal. Ale ten není perfektní. Mohl byste poradit podle logu z TeXstudia? Stejný problém i s Vaším iso-example.tex. Smazat složku v Temp, jsem zkoušel. Díky.

Proces spuštěn: biber.exe "dokumentace"

Use of uninitialized value $name in string eq at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/SortLists.pm line 77.

Use of uninitialized value $pre in regexp compilation at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 959. Use of uninitialized value $pre in regexp compilation at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 959. Use of uninitialized value $pre in regexp compilation at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 959. Use of uninitialized value $pre in regexp compilation at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 959. Use of uninitialized value $pre in regexp compilation at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 959. Use of uninitialized value $pre in regexp compilation at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 959. Use of uninitialized value $pre in regexp compilation at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 959. Use of uninitialized value $pre in regexp compilation at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 959. Use of uninitialized value $pre in regexp compilation at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 959. Use of uninitialized value $pre in regexp compilation at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 959.

Use of uninitialized value $pre in regexp compilation at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 959.

Use of uninitialized value $thislocale in concatenation (.) or string at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber.pm line 2767.

Use of uninitialized value $thislocale in concatenation (.) or string at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber.pm line 2854.

Use of uninitialized value $thislocale in concatenation (.) or string at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber.pm line 2859.

Use of uninitialized value $lname in concatenation (.) or string at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber.pm line 1929.

INFO - This is Biber 2.0
INFO - Logfile is 'dokumentace.blg'
INFO - Reading 'dokumentace.bcf'
WARN - Warning: Found biblatex control file version 2.6, expected version 2.7
INFO - Using all citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'literatura.bib' for section 0
INFO - Decoding LaTeX character macros into UTF-8
INFO - Found BibTeX data source 'literatura.bib'
INFO - Overriding locale '' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Overriding locale '' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Sorting list 'nyt' of type 'entry' with scheme 'nyt' and locale ''
INFO - No sort tailoring available for locale ''

Use of uninitialized value $lssn in concatenation (.) or string at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber.pm line 1929. Use of uninitialized value $lssn in concatenation (.) or string at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber.pm line 1943. Use of uninitialized value $lssn in concatenation (.) or string at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber.pm line 1958.

Can't use an undefined value as an ARRAY reference at C:\Users\DOMINI~1\AppData\Local\Temp\par-446f6d696e696b204d61747573\cache-8ae660f9043658766339c6aa38e5cfc48958bdda\inc\lib/Biber/Internals.pm line 949.

Proces ukončen s chybou(ami)

Proces spuštěn: pdflatex.exe -synctex=1 -interaction=nonstopmode "dokumentace".tex

Proces ukončen jako obvykle

**Comment by johannesbottcher** [comment]
`WARN - Warning: Found biblatex control file version 2.6, expected version 2.7`

Could as be as easy as updating `biblatex`?

**Comment by dominikmatus** [comment]
Thanks for quick response. It's so stupid mistake. I was confused, because I have updated everything, unfortunately biber too. And that is the problem. Downgrading ro biber version 1.9 worked. 
Just a question, can I change citations to superscript with iso-numeric?

**Comment by dominikmatus** [comment]
I found little bug, incolletion is not printing "Dostupný z WWW" (available from) before URL. So I edited iso.bbx and changed line to 
%\usebibmacro{availability
\usebibmacro{comment+link}{\mainlstring{url}}\usebibmacro{print-online}

**Comment by michal-h21** [comment]
Hi,

bibmacro `availability` should take care of it, if it doesn't print,
then maybe something is mising in the bib entry?

> I found little bug, incolletion is not printing "Dostupný z WWW" (available from) before URL. So I edited iso.bbx and changed line to
>
> %\usebibmacro{availability
> \usebibmacro{comment+link}{\mainlstring{url}}\usebibmacro{print-online}

**Comment by michal-h21** [comment]
Yeah, incompatible biblatex - biber versions are quite common
> Thanks for quick response. It's so stupid mistake. I was confused, because I
> have updated everything, unfortunately biber too. And that is the problem.
> Downgrading ro biber version 1.9 worked.

You can use  command `\supercite` to put numbers into superscripts

**Comment by dominikmatus** [comment]
Thank you guys. You are doing a great work. :)

**Comment by dominikmatus** [comment]
There is missing publication info for article. According to ISO 690, it should be printed. :)

**Comment by michal-h21** [comment]
What publication info do you mean? This is what I get for sample article:

DAMM, Werner; HAREL, David. LSCs: Breathing Life into Message Sequence
Charts. Formal Methods in System Design. 2001, roč. 19, č. 1, s. 45–80.

I don't see any missing info, except for ISSN, which was missing in the bib
file.

**Comment by DavidLuptak** [comment]
> There is missing publication info for article. According to ISO 690, it should be printed. :)

Replying to the missing publication info for an article entry raised in comment above https://github.com/michal-h21/biblatex-iso690/issues/11#issuecomment-107059914 (not a primary topic of this issue, though):

I suppose that by publication info are meant location and publisher information of the journal or magazine in which an article is published. These two fields are not required nor optional fields for an `@article` entry type from the `biblatex` documentation point of view. Citation managers like Mendeley or Zotero doesn't even provide fields for these values. Online services like Springer Link can export `bib` file and again, there is no location and publisher fields included.

However, standard ISO 690 says that this information is required (informative appendix B.4.2). [The Czech interpretation](https://www.citace.com/CSN-ISO-690.pdf) put a note on this that location and publisher info are not necessary for identification of a document, so they could be left out (page 6, 'Příspěvek (článek) v periodiku', 'Pozn.').

In case anybody would need these fields for an `@article` entry type, it is supported since cdeb5c098bae876e2b9a5f030ae853f9b7d489cd.

Closing this issue.

**Comment by DavidLuptak** [comment]
I've just found this comprehensive [answer on Stack Exchange](https://tex.stackexchange.com/a/438997) by @moewew, that also elaborates the sub-issue about publisher + location for `@article`. To sum up, I hope nothing breaks if we use `\usebibmacro{location+publisher+date}` instead of `\usebibmacro{date}` in the `@article` driver.

**Comment by DavidLuptak** [comment]
In the end I decided to add a package option `articlepubinfo` for this which is disabled by default, see 8a609d9988a3f9433d54f4af1ba334a2187ca0b8.
