### ISSUE TITLE
InBook: missing comma with multiple editors

### ISSUE THREAD

**Issue by africola** [michal-h21/biblatex-iso690#117]
# Issue

When using an `@InBook` bibliography entry with three or more editors, there is no comma between the names of the first and second editor.

This applies to biblatex-iso690 version 0.4.1 (2022-03-20), the current version.

# Steps to reproduce

The following is an MWE:

```
\documentclass{article}
\usepackage[style=iso-authoryear]{biblatex}
\begin{filecontents}{test2.bib}
@InBook{Pollak2006,
  author    = {Pollak, Robert A.},
  booktitle = {Samuelsonian Economics and the Twenty-First Century},
  date      = {2006},
  title     = {Samuelson's ``Dr. Jekyll and Mrs. Jekyll'' problem: A Difficulty in the Concept of the Consumer},
  editor    = {Michael Szenberg, Lall Ramrattan, Aron A. Gottesman},
  foreword  = {Arrow, Kenneth J.},
  isbn      = {0-19-929883-1},
  pages     = {116--126},
  publisher = {Oxford University Press},
}
\end{filecontents}
\addbibresource{test2.bib}
\begin{document}
\cite{Pollak2006}
\printbibliography
\end{document}
```

# Actual output

![image](https://user-images.githubusercontent.com/12384441/166223670-5335d0cd-fd3e-411a-870d-8e778786de17.png)

# Expected output

The same as the actual output, but with a comma after "Szenberg" and before "Lall".

# Additional comments

The capitalization of first and last names of the editors is inconsistent. I don't have access to the ISO 690 standard and can't say whether this is intentional, but I would suggest reviewing whether this is correct.

**Comment by moewew** [comment]
There is a small problem with the input in the example. Independent of the desired output all names must be separated with `and`. Commas are only used to separate parts of the same name (given and family names). See for example https://tex.stackexchange.com/q/36396/35864

With the correct input you get consistent output
```latex
\documentclass{article}
\usepackage[style=iso-authoryear]{biblatex}
\begin{filecontents}{\jobname.bib}
@InBook{Pollak2006,
  author    = {Pollak, Robert A.},
  booktitle = {Samuelsonian Economics and the Twenty-First Century},
  date      = {2006},
  title     = {Samuelson's ``Dr. Jekyll and Mrs. Jekyll'' problem: A Difficulty in the Concept of the Consumer},
  editor    = {Michael Szenberg and Lall Ramrattan and Aron A. Gottesman},
  foreword  = {Arrow, Kenneth J.},
  isbn      = {0-19-929883-1},
  pages     = {116--126},
  publisher = {Oxford University Press},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\cite{Pollak2006}
\printbibliography
\end{document}
```
> POLLAK, Robert A., 2006. Samuelson’s “Dr. Jekyll and Mrs. Jekyll” problem: A Difficulty in the Concept of the Consumer. In: Samuelsonian Economics and the Twenty-First Century. Ed. by SZENBERG, Michael; RAMRATTAN, Lall; GOTTESMAN, Aron A. Oxford University Press, pp. 116–126. isbn 0-19-929883-1.

![screenshot of the output shown above](https://user-images.githubusercontent.com/6755835/166229198-42eaf9af-6e7f-419e-a598-8c7fd63209b0.png)

**Comment by africola** [comment]
@moewew Thank you very much for the pointer; that solved it. This issue can be closed as invalid then.
