### ISSUE TITLE
Define `urlseen` bibliography string for Czech

### ISSUE THREAD

**Issue by Witiko** [michal-h21/biblatex-iso690#121]
The `urldate` field produces the `urlseen` bibliography string in the output:

https://github.com/michal-h21/biblatex-iso690/blob/58cd557020786b14c003ff50d23772498509031b/iso.bbx#L397

The `urlseen` bibliography string is not defined for Czech by us:

https://github.com/michal-h21/biblatex-iso690/blob/58cd557020786b14c003ff50d23772498509031b/czech-iso.lbx#L16-L17

However, it is likely defined by BibLaTeX and expands to `cit.`, which is correct according to the ČSN ISO 690-2:2000 norm, but has apparently been replaced by `vid.` in the newer ČSN ISO 690:2011 and ČSN ISO 690:2022 norms, although I don't have the newer norms on me to check.

**Comment by michal-h21** [comment]
I don't know about ČSN ISO 690:2022, but I think that in the 2011 version, the `cit.` string was used. From [this Citakon  conference presentation](https://www.citakon.cz/prezentace/2022/Co-prinese-nova-norma-CSN-ISO-690.pptx) (slide 9), it seems that the preferred term could be "zobrazeno" or similar term. More serious change is that it should be placed at the end of the citation. I am not sure that the new Czech version of ISO 690 had been already published, but it seems that it would need a lot of changes.

**Comment by Witiko** [comment]
> I don't know about ČSN ISO 690:2022, but I think that in the 2011 version, the cit. string was used.

I will need to check, I am going by information given by an anonymous reviewer, which may be wrong.

**Comment by michal-h21** [comment]
Maybe it is a local recommendation at MUNI? I've found [this document](https://is.muni.cz/do/rect/el/estud/lf/js22/citacni_styly/web/pages/ISO_webpage.html), that recommends `vid.`, but it is the only one I could find. Others, from CUNI, ZCU, and Citace.com, all used `cit.`.

**Comment by Witiko** [comment]
The reviewer should not come from MUNI, but they may have been confused by the same document. I will ask the libratians from MUNI why they recommend vid. instead of cit.

**Comment by Witiko** [comment]
@michal-h21 I asked the authors of [the document that you linked][1] and I received the following response (in Czech):

 [1]: https://is.muni.cz/do/rect/el/estud/lf/js22/citacni_styly/web/pages/ISO_webpage.html

> Dobrý den,
> 
> Vámi zmíněná norma ČSN ISO 690-2:2000 je již více jak deset let neplatná. Aktuálně je platná verze z roku 2011, ve které se používá zkratka vid. jako překlad anglické předlohy viewed. V případě potřeby na https://katalog.muni.cz/Record/MUB01000673383 seznam knihoven, ve kterých je norma z roku 2011 k nahlédnutí.
>
> Pokud jde o přístupnost zkratky "cit.", tak v normě se mj. píše "Příklad použité v této mezinárodní normě nejsou předepisující, pokud jde o styl a interpunkci." Mám za to, že zkratka cit./vid. do tohoto nespadá, takže bych používal zkratku vid. (pro tu je ostatně i nastaven citační styl na https://www.zotero.org/styles používaný i v Mendeley nebo CitacePRO.
>
> Zdraví   
> Jiří Kratochvíl

I can pop into the FI MUNI library tomorrow and see what the norm says.

**Comment by michal-h21** [comment]
They seem to be right about the style in Zotero, but CitacePRO uses `cit.`. Their author even uses it in his [recent book](https://www.pablikado.cz/dokument/rTgNP6REv1DE6fte). So I think we need to take a look at the norm itself. We used to have it in the library, but I cannot find it now, so if you will be able to take a look, it would be great.

**Comment by Witiko** [comment]
@michal-h21 
![20221018_103915](https://user-images.githubusercontent.com/603082/196381965-791258e5-42b2-41f0-ba86-ad12b9ab0fd6.jpg)

**Comment by michal-h21** [comment]
@Witiko thanks for the clarification, it seems quite obvious now. I've changed the bibliography strings for Czech to incorporate it.
