### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by spaceKelan** [michal-h21/biblatex-iso690#128]
Hi Michal,

I am not very experienced with adding "external" packages to latex. I tried multiple things like placing the files I think I need to my project root directory 
![image](https://github.com/michal-h21/biblatex-iso690/assets/51329415/e84c887a-499f-4156-9058-a5f4bab84755)

I used biblatex and biber and it works well, but they don't want to "see" your styles. 

In the precise README you say locate it in `$TEXMFHOME/tex/latex`, but I am restricted to Windoofs in this matter and my search is broken due to some updates.

So when I try to find some path like this, there is no texmf file and I cannot use terminal commands because Powershell is a whole new story to me.
![image](https://github.com/michal-h21/biblatex-iso690/assets/51329415/4fe1cec4-f511-4c51-8546-3487d9967dd9)

Do you have any advise of what I should do?

I use `texlive 2023` and `TexStudio`

Thanks in advance

**Comment by michal-h21** [comment]
You don't need to edit the `texmf.cnf` file. Location of the `texmf` dir should print this command:

      kpsewhich --var-value TEXMFHOME

Just copy it to the command prompt and press enter. It should print the path to the dir. Note that it is possible that it doesn't exist, so you will need to create it. Then, you need to create also `tex/latex/` subdirectories.

**Comment by spaceKelan** [comment]
Thanks for your quick reply

In powershell I receive the output
```
C:/Users/<my_user>/texmf
```
but when I go to that path, I do not see this directory ( hidden files visible).

I did do the following now:
1. I created the folder hierarchy
```
C:/Users/<my_user>/texmf/tex/latex/
```
2. I moved the unpacked `biblatex-is0-690`in there 
3. In a LaTeX editor: I cleaned the auxilary files and tried built the project again:
```latex
\usepackage[backend=biber, sorting=iso-numeric]{biblatex}
```
 It does not recognize the `iso-numeric` - what am I doing wrong?

**Comment by michal-h21** [comment]
This should be correct procedure. Does this command print a path to the file?

      $ kpsewhich iso-numeric.bbx

**Comment by spaceKelan** [comment]
Yes, it does
```
c:/Users/<nmy_user>/texmf/tex/latex/biblatex-iso690/iso-numeric.bbx
```

weirdly with a lowercase c, which might be an issue for the case-sensitive file system

**Comment by michal-h21** [comment]
Ah, now I see the issue, you use 

```latex
\usepackage[backend=biber, sorting=iso-numeric]{biblatex}
```

instead of 

```latex
\usepackage[backend=biber, style=iso-numeric]{biblatex}
```

**Comment by spaceKelan** [comment]
Ah nice, thanks - my bad! Now it works

One more question. According to my knowledge of ISO 690:2010 the naming convention is LAST NAME, First name, first name, LAST NAME, , first name, LAST NAME, first name, LAST NAME and then "et al" comes. But here I observe LAST first LAST first ...

**Comment by michal-h21** [comment]
I think you can request this form of names using the `givennamesfirst` option.
