### ISSUE TITLE
Author surnames in capitals?

### ISSUE THREAD

**Issue by henczati** [michal-h21/biblatex-iso690#13]
Hi!

I'm not familiar with the international ISO 690:2010, but in all the examples for the Czech translation (CSN ISO 690:2011) I saw so far the surnames of the authors were written in either all capitals or in a small-caps font.

If this is not part of the international ISO, is there an option to switch this behaviour on?  Or if not, could it be added?

**Comment by johannesbottcher** [comment]
I am currently working on updating the whole thing. But it takes some time as we all have some other occupation as well ;-). I have talked to the maintainer, he also has a bit of other stuff on his mind.

**Comment by henczati** [comment]
I imagine :).
Do you think it would be in a usable state before the end of July? I would appreciate it.
Too bad I know nothing about biblatex or any other latex coding myself.

**Comment by johannesbottcher** [comment]
Yes, i think so. Really, most of the stuff is already implemented by the standard styles, truncating too long lists is the only *important* thing to do, and this will be optional. Do you need support for audio, video and similar material? If so, it will rise in importance.

**Comment by henczati** [comment]
No, thanks for asking. So far, I use only written references (on paper and electronically), and I don't expect this to change until that deadline. If it did, I will ask nicely :).

However, I think I will need this all-caps/small-caps surnames feature. I am going to ask my supervisor about it later, just to make sure ;-). Department traditions/conventions play a significant part in such matters.

**Comment by michal-h21** [comment]
Hi,
try to add to the document preamble this command:

\renewcommand\mkbibnamelast[1]{#1}

if that works, we may add some package option for this

**Comment by henczati** [comment]
Hi,
I got back to biblatex only now.
Pulled the latest master, and saw that the author surnames are capitalized by default in the bibliography.
Thank you very much.

p.s.: If anyone else would stumble upon this issue, just to try, I added
```latex
\renewcommand\mkbibnamelast[1]{#1}
```
to the preamble, and now it changes the surnames back to the normal way (with only the first letter capitalized).

**Comment by DavidLuptak** [comment]
Now we use `\familynameformat` for that.

See https://github.com/michal-h21/biblatex-iso690/wiki/Style-Guide#format-of-the-surname-last-name-family-name-addressing-13.
