### ISSUE TITLE
Missing support for "@Patent" entry type

### ISSUE THREAD

**Issue by hunator** [michal-h21/biblatex-iso690#14]
If I use Patent entry in DB (*.bib file) and try to \autocite{...} it. PDFLaTeX returns:
!Package biblatex Error: No driver found \printbibliography{

In document there would be only number not written entry. Biber works just fine, without error/warning.

After change to entry type "@online" everything works again (but doesn't show number = {...}).

Here is used entry:
@Patent{johnson2007,
    author = {Johnson, J.D. and Zarabadi, S.R. and Jay, I.D.},
    month = apr,
    number = {US Patent 7,204,162},
    publisher = {Google Patents},
    title = {{Capacitive strain gauge}},
    url = {https://encrypted.google.com/patents/US7204162},
    urldate = {2015-06-02},
    year = {2007}
}

Presumably it is due missing support of "@Patent" entry type.

**Comment by johannesbottcher** [comment]
Confirmed, as a fix i will provide the standard definition right here and now, please add it to your document preamble. ISO690 might differ,  i need to take a closer look at this. Update coming in the following days. 

```latex
\DeclareBibliographyDriver{patent}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author}%
  \setunit{\labelnamepunct}\newblock
  \usebibmacro{title}%
  \newunit
  \printlist{language}%
  \newunit\newblock
  \usebibmacro{byauthor}%
  \newunit\newblock
  \printfield{type}%
  \setunit*{\addspace}%
  \printfield{number}%
  \iflistundef{location}
    {}
    {\setunit*{\addspace}%
     \printtext[parens]{%
       \printlist[][-\value{listtotal}]{location}}}%
  \newunit\newblock
  \usebibmacro{byholder}%
  \newunit\newblock
  \printfield{note}%
  \newunit\newblock
  \usebibmacro{date}%
  \newunit\newblock
  \usebibmacro{doi+eprint+url}%
  \newunit\newblock
  \usebibmacro{addendum+pubstate}%
  \setunit{\bibpagerefpunct}\newblock
  \usebibmacro{pageref}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{finentry}}
```

**Comment by hunator** [comment]
Hi @johannesbottcher , thanks for a reply. That fixed original problem but added few more (4 of undefined macros).

! Package biblatex Error: Bibliography macro 'doi+eprint+url' undefined.
! Package biblatex Error: Bibliography macro 'addendum+pubstate' undefined.
! Package etoolbox Error: Toggle 'bbx:related' undefined.
! Package biblatex Error: Bibliography macro 'finentry' undefined.

For now I can use "online", I have about month of time so you don't have to rush because of me. If you would have any other fix, I'll be happy to test that (I'll be monitoring this thread).

Thank you once again for a really quick response.

**Comment by johannesbottcher** [comment]
To be honest, i didn't test my suggested fix. It will probably be a good idea to load all the standard stuff (including the needed bibmacros) within `iso.bbx` and just add required fixes/customizations.

**Comment by michal-h21** [comment]
Yes, I started biblatex-iso from scratch and I haven't really used standard
biblatex styles, also biblatex development is much faster than development
of biblatex-iso, so incompatibilities may happen with every new biblatex
release. It seems that best thing to do might be to start again with
standard biblatex styles and only adapt parameters and modify only
necessary macros. One thing in which ISO 690 is really difficult is the
usage of different languages (language of cited publication and language of
the document) within one entry, the other speciality are descriptions for
online material ("Available comercially from:", "Available also from:"
etc.) So we must support at least that.
