### ISSUE TITLE
iso-numeric \textcite writes all author names in all-caps before [number]

### ISSUE THREAD

**Issue by henczati** [michal-h21/biblatex-iso690#18]
E.g. for 5 authors:

> text FIRST; SECOND; THIRD; FOURTH; FIFTH [1] othertext

If `\textcite` has to write authors in numeric style, I think

> text First et al. [1] othertext

(suggested in #12) would be the way to go.

**Comment by moewew** [comment]
To change `\textcite` only you can add
```
\makeatletter
\renewrobustcmd{\cbx@textcite@init}[2]{%
  \renewcommand{\mkbibnamelast}[1]{##1}%
  \setcounter{textcitetotal}{0}%
  \setcounter{textcitecount}{0}%
  \def\cbx@savedcites{#1}#2\cbx@savedcites\empty}
\makeatother
```
to your preamble.

If you want to also have `\citeauthor` and friends output "normal" capitalisation, go with

```
\renewcommand*{\mkbibnamelast}[1]{#1}
\AtBeginBibliography{\renewcommand*{\mkbibnamelast}[1]{\MakeUppercase{#1}}}
```

**Comment by DavidLuptak** [comment]
Explained, closing.
