### ISSUE TITLE
gap between fields

### ISSUE THREAD

**Issue by dirceuBarquette** [michal-h21/biblatex-iso690#20]
Firstly congrat! Great job!

Here is the problem:
![bib_question](https://cloud.githubusercontent.com/assets/76786/11547035/2410985c-9938-11e5-9652-d0f72703748a.png)

The entry:
```
@article{leitao1985questao,
	title={A quest{\~a}o organizacional na universidade: as contribui{\c{c}}{\~o}es de Etzioni e Rice},
	author={Leit{\~a}o, Sergio Proen{\c{c}}a},
	journal={Revista de Administra{\c{c}}{\~a}o P{\'u}blica},
	volume={19},
	number={4},
	pages={3-26},
	year={1985}
}
```
Where is my mistake?
Thanks
Barquette

**Comment by michal-h21** [comment]
Could you please post also code snippet with `\usepackage[options]{biblatex}`? And some details about your TeX distro, do you use current TeX Live?

**Comment by dirceuBarquette** [comment]
I'm using a 2015 texlive from CTAN. My  distro is opensuse wich has obsolete packages.

```
\usepackage[
backend=biber
,backref=true
,style= iso-numeric
%    ,style= iso-authoryear
%,autolang=other
,sortlocale=pt_br
,bibencoding=UTF8
,block=none
,autolang=hyphen
]{biblatex}
```
Thanks

**Comment by dirceuBarquette** [comment]
Sorry! Forgot he preamble...

```
\documentclass[
% -- opções da classe memoir --
12pt,                           % tamanho da fonte
openright,                      % capítulos começam em pág ímpar (insere página vazia caso preciso)
twoside,                        % para impressão em verso e anverso. Oposto a oneside
a4paper,                        % tamanho do papel. 
% -- opções da classe abntex2 --
chapter=TITLE,         % títulos de capítulos convertidos em letras maiúsculas
section=TITLE,         % títulos de seções convertidos em letras maiúsculas
subsection=TITLE,      % títulos de subseções convertidos em letras maiúsculas
subsubsection=TITLE,% títulos de subsubseções convertidos em letras maiúsculas
sumario=abnt-6027-2012
% -- opções do pacote babel --
english,                        % idioma adicional para hifenização
french,                         % idioma adicional para hifenização
spanish,                        % idioma adicional para hifenização
brazil                          % o último idioma é o principal do documento
]{abntex2}
```

**Comment by michal-h21** [comment]
Ah, it seems related to `abntex2` class. I see options for `babel` are passed to it, I suspect it redefines some of it's internals and it produces spurious whitespaces. We use babel's language switching mechanism for printing of some field labels.

If you don't have to follow the requirement that certain fields should be printed in main document language, you can try to put the following redefinitions to your preamble:

     \renewcommand\mainsstring[1]{\bibsstring{#1}}
     \renewcommand\mainlstring[1]{\biblstring{#1}}

**Comment by dirceuBarquette** [comment]
Great!!! It works!!!!

Thank you very much!

After I'll verify about "certain fields should be printed in main document language", because I need to put references at footnote too.
