### ISSUE TITLE
Editor can't be omitted in @incollection

### ISSUE THREAD

**Issue by martin-wo** [michal-h21/biblatex-iso690#21]
If I omit the editor field in "@incollection" entry type, a period remains after the "In" preposition in the resulting citation. The period should be removed, in case there is no editor.

Thanks in advance

**Comment by moewew** [comment]
Normally one would expect a `@collection` (and thus an `@incollection`) to have an `editor`.

In any case the problem can be solved by changing [line 519 in `iso.bbx`](https://github.com/michal-h21/biblatex-iso690/blob/master/iso.bbx#L519) from 

```
\setunit{\intitlepunct}
```

to

```
\printunit{\intitlepunct}%
```

@michal-h21 if you like I can commit a fix to that effect.

**Comment by michal-h21** [comment]
>      \setunit{\intitlepunct}
>
> to
>
>     \printunit{\intitlepunct}%
>
>  @michal-h21 if you like I can commit a fix to that effect.

@moewew thanks, I woult be really happy if you want to fix any issues, you have much better expertise in Biblatex :)

**Comment by moewew** [comment]
I have committed a fix for the issue (and apparently immediately closed it as well, that was not the intention ... it is re-opened now). 

Please pull the latest version.
