### ISSUE TITLE
Oddělovač jmén autorů

### ISSUE THREAD

**Issue by Kobzol** [michal-h21/biblatex-iso690#22]
Když použiji u knihy více autorů, jejich jména jsou oddělená pomocí středníku (;), přitom podle standardu by měly být oddělené čárkou a před posledním autorem by mělo být "a" (https://sites.google.com/site/novaiso690/prvky-citace/tvuarce). Je možné toto chování nějakým příkazem upravit?

**Comment by johannesbottcher** [comment]
A famous translation service used by DPC gives us: 
>When I use books with more authors, their names are separated by semicolons (;), while according to the standard should be separated by a comma and before the last author should be "a" (https://sites.google.com/site/novaiso690/ elements-quotes / tvuarce). It is possible that some order to modify behavior?

**Comment by Kobzol** [comment]
Wow, that's actually a very good machine translation :-) I wasn't sure what language to use here, I'll restate it in english.
If I use multiple authors for a book, their names are separated with a semicolon (TANENBAUM, Andrew S.; WOODHULL, Albert S.). The names should be separated by a comma and the last author's name should be separated with "a" (and in Czech language), according to the ISO 690:2011 Czech citation standard.
Is it possible to modify this behavior in some way?

**Comment by johannesbottcher** [comment]
I did not look into the standard, but here you go:

```lang=latex
\renewcommand\multinamedelim{\addcomma\space}
\renewcommand\finalnamedelim{\addspace\bibstring{and}\space}
```

The original would be 
```lang=latex
  \newcommand*{\finalnamedelim}{%
  \ifnumgreater{\value{liststop}}{2}{\finalandcomma}{}%
  \addspace\bibstring{and}\space}
```

**Comment by Kobzol** [comment]
Thank you very much, It worked fine :-)
I just removed the \bibstring, because the "and" was in bold.

**Comment by johannesbottcher** [comment]
@Kobzol If it was in bold, something in your installation of biblatex is not right or the language you are using is unknown. For me. the definition gives *und* if `ngerman` is passed to `babel`, *and* if english is passed and *a* if czech i passed.

**Comment by moewew** [comment]
I cannot say anything about what the "correct" output would be according to the standard (though I have seen semicolons in many German implementations of ISO/DIN citation styles). Currently this is done in [ll. 82-83 of `iso.bbx`](https://github.com/michal-h21/biblatex-iso690/blob/master/iso.bbx#L82):
```
\renewcommand\multinamedelim{\addsemicolon\addspace}
\renewcommand\finalnamedelim{\multinamedelim}
```

The search shows `\multinamedelim` cropping up in https://github.com/michal-h21/biblatex-iso690/issues/10 as well.

Indeed, as @johannesbottcher points out, there should be no need to get rid of the `\bibstring` it should work (except of course if your language is not supported by `biblatex`).

**Comment by Kobzol** [comment]
Sorry, the bold part was a fault on my side, I replaced the \bibstring{and} with \bibstring{a}, I didn't realize, that it's a label, not a literal string. But with this, it shows the wrong string.
I use \usepackage[english, czech]{babel} for babel, babel=other in biblatex and hyphenation=english for the book.
The book is written in English, while my thesis is written in Czech.
If I use the hyphenation=english and \bibstring{and}, it uses the string "and".
But according to the standard, this field should be localized in the document's language, not the book's language, so it should be "a".

**Comment by moewew** [comment]
Yes, I heard about that "some strings need to be in the original, some in the document language" madness. 

Try `\mainsstring`instead of `\bibstring`in this case.

**Comment by Kobzol** [comment]
Yeah, that's a very "interesting" part of the standard.
Thank you, `\mainsstring` worked perfectly :-)
