### ISSUE TITLE
`inbook` entry type 

### ISSUE THREAD

**Issue by michal-h21** [michal-h21/biblatex-iso690#26]
Recent biblatex changes highlighted problems with `inbook` entry type:

KOLLMANNOVÁ, Ludmila; BUBENIKOVÁ, Libuše; KOPECKÁ, Alena1977. Angličtina pro sa-
mouky. 5. vyd. NOVOTNÁ, Pepina. Praha: Státní pedagogické nakladatelství. 2. Podkapitola,
s. 22–29. ISBN 80-04-25663-5.

This format is wrong, it should be:

NOVOTNÁ, Pepina, 1977.  2. Podkapitola. In: KOLLMANNOVÁ, Ludmila; BUBENIKOVÁ, Libuše; KOPECKÁ, Alena.  Angličtina pro samouky Praha: Státní pedagogické nakladatelství., s. 22–29. ISBN 80-04-25663-5.

I have one more question, the source for this record is this crossreference:

@BOOK{koll,
  author = {Kollmannová, Ludmila and Bubeníková, Libuše and Kopecká, Alena},
  title = {Angličtina pro samouky},
  edition = {5},
  location = {Praha},
  publisher = {Státní pedagogické nakladatelství},
  year = {1977},
  pagetotal = {525},
  series = {Učebnice pro samouky},
  isbn = {80-04-25663-5}
}

@INBOOK{kap,
  author = {Novotná, Pepina},
  title = {Podkapitola},
  pages = {22-29},
  chapter = {2.},
  crossref = {koll}
}

You can see that both chapter and title are used in @INBOOK, I suspect that this isn't a correct way.

**Comment by moewew** [comment]
Mhhh, we have 
```
\DeclareBibliographyDriver{inbook}{%
%\printnames{author}%
\usebibmacro{bibindex}%
\usebibmacro{begentry}%
\printnames{bookauthor}%
\usebibmacro{year-label}%
\newunit\newblock%
% \printfield{booktitle}%
% \printfield[emph-colon]{booksubtitle}%
\usebibmacro{pub:title}%
\newunit\newblock%
\usebibmacro{book:vol}%
\newunit\newblock%
\printnames{author}%
```

probably `bookauthor` and `author` should be switched then.

**Comment by DavidLuptak** [comment]
@michal-h21 Yes, you are definitely right. The norm ISO 690:2011 stated format as you wrote as it should be. But, in the whole text of the norm, term chapter is not mentioned (but I may be wrong).
Your suspicion is reasonable. Title of the contribution is not the correct place for the chapter value. There might be possible place for it before range of page numbers, because in the norm there is mentioned required element called Numeration, which should be numeration of volume, etc. containing the contribution.

**Comment by DavidLuptak** [comment]
@moewew @michal-h21 I propose a correction for this issue:
```latex
\DeclareBibliographyDriver{inbook}{%
%\printnames{author}%
\usebibmacro{bibindex}%
\usebibmacro{begentry}%
\usebibmacro{names:primary}%
\setunit{\labelnamepunct}\newblock%
\printfield{title}%
\setunit{\addspcolon\addspace}%
\printfield{subtitle}%
\setunit{\addspace}%
\printfield{addon}%
\newunit\newblock%
\usebibmacro{in}%
\printunit{\intitlepunct}%
\printnames{bookauthor}%
\newunit\newblock%
\usebibmacro{pub:title}%
\newunit\newblock%
\usebibmacro{book:vol}%
\newunit\newblock%
\usebibmacro{book:pubinfo}%
\newunit\newblock%
%\printfield{chapter}%
%\setunit*{\addcomma\addspace}%
%\newunit%
\setunit{\addcomma\addspace}%
\printfield{pages}%
\newunit\newblock%
...
```
with omitting chapter value at all in bibliography reference.

**Comment by moewew** [comment]
I can't comment on how things should look like. But the code provided looks absolutely fine. `author` and `bookauthor` are in the right place now.

I would find it not unreasonable to add the chapter before the page numbers at the end, but then they would certainly need an accompanying bibstring (`\DeclareFieldFormat{chapter}{\bibstring{chapter}~#1}`).

**Comment by DavidLuptak** [comment]
@moewew Thank you for your suggestion. I have included chapter value there, a little bit according to previous version of the ISO 690 norm, I would say -- because I have found an example showing
> ... Place: Publisher. Chapter 'X', pp. 'Y'--'Z'. ...

But I am not able to deal whether there should be a comma rather than a dot, as follows
> ... Place: Publisher, chapter 'X', pp. 'Y'--'Z'. ...

**Comment by michal-h21** [comment]
@DavidLuptak I will take a look at the norm itself tomorrow, I can't find examples with chapter for the current version. It is a question whether the chapter should be included, given that the chapter title is already used after the chapter author.

**Comment by michal-h21** [comment]
So there is no information about chapters in the norm itself, other than "other information can be included at suitable places" :D 

I like the 

     ... Place: Publisher, chapter 'X', pp. 'Y'--'Z'. ...

form more, as it follows logic of of `Place: publisher, location.`

**Comment by DavidLuptak** [comment]
Already implemented as proposed, closing.
