### ISSUE TITLE
Document url availability is using wrong language

### ISSUE THREAD

**Issue by Kobzol** [michal-h21/biblatex-iso690#31]
All my references that have a url field contain the message "Available (also) from WWW: <url>".
But my document is in czech language, so this message should be written in czech, if I'm not mistaken (it can be seen here: https://sites.google.com/site/novaiso690/specificke-zdroje/elektronicke-informacni-zdroje).

This is my package setup:
```
\usepackage[czech]{babel}
\usepackage[
	backend=biber,
	autolang=other,
	babel=other,
	style=iso-numeric,
	sorting=none,
	sortlocale=cs_CZ,
  bibencoding=UTF8]{biblatex}
```

**Comment by michal-h21** [comment]
It works for me, do you use `\usepackage[czech]{babel}` in your document?

**Comment by Kobzol** [comment]
Yes, I have that line just above the biblatex package, as shown in the code snippet that I posted here.

**Comment by Kobzol** [comment]
A document class that I was using was causing it. It was selecting multiple languages for babel and I have to alter it to use the `main=czech` option. Problem solved, thank you :-)
