### ISSUE TITLE
Anonymous works

### ISSUE THREAD

**Issue by DavidLuptak** [michal-h21/biblatex-iso690#46]
The norm states that term “Anon” may be used instead of a creator's name when citing in author-year style. Another case somehow related to this is also that for certain kinds of information resources (e.g. encyclopaedias, films, conferences, etc.), the title should be used instead of creator.

How can we manage to print the term "Anon" in the citation when no author (or any other creator) is entered in .bib file?
How can we manage to differentiate that the title can be used instead of creator and how to print it in respective place?

I was trying to hack the macro `cite` in `author-year.cbx`, but ended up with [this issue reported by @moewew](https://github.com/plk/biblatex/issues/334) to biblatex project. Is it then even possible to achieve this?

Of course, the naive approach is to fill up the author field in .bib file with the value "Anon", but this is not applicable for that kinds of entry types in which the title should be used instead of creator.

**Comment by DavidLuptak** [comment]
Somehow the solution for my questions is provided by default by the biblatex package. I have found respective chapter 2.3.2 in the documentation, `title` is used as a fallback if no creator is entered in .bib file, as well as the field `label` is served for this purpose.

Well, printing the term "Anon" is left to the creator of .bib file.

**Comment by michal-h21** [comment]
I've added some basic info about this to iso-example.tex.
