### ISSUE TITLE
Compilation problem - undefined 'urldate' macro

### ISSUE THREAD

**Issue by NefariousOctopus** [michal-h21/biblatex-iso690#47]
Hi,

I have issues with compiling even this minimalistic tex file:

> Package biblatex Error: Bibliography macro 'urldate' undefined.

the error is reported on line with `\printbibliography`

```latex
\documentclass{article}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage[autostyle]{csquotes}

\usepackage[
backend=biber 
,style=iso-numeric          
,autolang=other
,sortlocale=en_US
,bibencoding=UTF8
]{biblatex}

\addbibresource{mybib.bib}

\begin{document}
 \cite{kniha} \cite{t00}

\printbibliography
\end{document}
```

It seems that this problems only affects me. I suppose that I do something terribly wrong.

Any ideas? Thanks

EDIT: The bibliography is your testing .bib file

**Comment by moewew** [comment]
I tested the exact MWE you gave with the code from the master branch and got no such error (I also tested it with a slightly older version of the code, but can't give the version exactly).

Indeed, I would be surprised to see `urldate` undefined, it is defined in `biblatex.def` (in 3.3 `biblatex_.def`) which is always loaded.

What version are you using? Can you pull the latest code from the master branch and try again? Make sure that `biblatex` is up to date as well. If that does not work, please consider showing the `.log` file.

**Comment by NefariousOctopus** [comment]
Sorry, it was an outdated `biblatex`. 

Thank you for your time.
