### ISSUE TITLE
Translation guideline

### ISSUE THREAD

**Issue by Crissov** [michal-h21/biblatex-iso690#49]
It would be nice to have a small sample document to show how the new strings – currently ‘at’, ‘bysupervisor’ and ‘urlalso’ – will be used, so translators can better decide on the best translation. For #48, I took my best shot based upon the code in [iso.bbx](https://github.com/michal-h21/biblatex-iso690/blob/master/iso.bbx), I did not check a German DIN or Austrian ÖNORM:

``` latex
%location
\newbibmacro*{location}{%
  \iffieldundef{library}
    {}
    {\usebibmacro{at:}%
     \printfield{library}}%
}
…
\newbibmacro*{at:}{%
  \printtext{\mainsstring{at}\intitlepunct}%
}

\DeclareFieldFormat{supervisor}{%
  \mainlstring{bysupervisor}\addspace#1}
…
\newbibmacro*{thesissupervisor}{%
  \ifnameundef{supervisor}
    {}
    {\printtext{\mainlstring{bysupervisor}}%
     \addspace%
     \printnames{supervisor}}
}

\DeclareFieldFormat*{url}{%
  \iffieldundef{urlyear}
  {\mainlstring{urlalso}\addcolon\space\url{#1}}
  {\mainlstring{urlfrom}\addcolon\space\url{#1}}
}
```

**Comment by DavidLuptak** [comment]
Let me introduce a first draft of such guideline at the wiki pages dedicated to the repository: <https://github.com/michal-h21/biblatex-iso690/wiki/Translation-Guideline>. It's a appropriate excerpt right from the ISO 690 standard + examples.

**Comment by michal-h21** [comment]
@DavidLuptak that's perfect, thanks a lot!
