### ISSUE TITLE
in order to compile (without warning) I need csquotes package

### ISSUE THREAD

**Issue by Kyslik** [michal-h21/biblatex-iso690#53]
`$ pdflatex my.tex`

>Package biblatex Warning: 'babel/polyglossia' detected but 'csquotes' missing.
(biblatex)                Loading 'csquotes' recommended.

```
\usepackage[english,slovak]{babel}
\usepackage[utf8]{inputenc}
\usepackage[style=german]{csquotes} % <-------------------- especially this line
% package for biblatex https://github.com/michal-h21/biblatex-iso690
\usepackage[backend=biber,style=iso-numeric,autolang=other,bibencoding=utf8]{biblatex}
.
.
.
```

I use german `csquotes` because they are same for Slovak / Czech / Polish style...  
>**Note**: `\usepackage[autostyle]{csquotes}` seems to work as well

I am using MacTex distro.

**Comment by moewew** [comment]
Mhhh, I'm not following. What exactly is your question here?
`biblatex` just tells you that it is a good idea to use `csquotes` in a multilingual document (or rather one that loads `babel`/`polyglossia`). You are of course free to ignore that warning. - It is a warning after all.

**Comment by Kyslik** [comment]
@moewew sure, I am free to ignore warnings but I like to have no warnings... if anyone looks for `csquotes warning`, one is going to land here. 

---

If you follow recommendation **use csqotes package** you simply do `\usepackage{csquotes}` which produces another  warning

>Package csquotes Warning: No style for language 'slovak'.
(csquotes)                Using fallback style on input line 10.

Now you do something like `\usepackage[slovak]{csquotes}` (or `[czech]` which produces error. You can use `[german]` or `[autostyle]` which produce no warnings nor errors.

Čeers. (you are free to close this)

**Comment by moewew** [comment]
Aha! So his was rather meant as a 'help thread' rather than a bug report/feature request?

Yes, `csquotes` has no predefined paterns for `slovak` or `czech`, if you write in those languages you will have to define them yourself or find a way round (use `german` for example, if that works for you), see also http://tex.stackexchange.com/q/166337/ on TeX.SX. (I believe that `autostyle` should actually give a warning if the main language of the document is Czech or Slovakian.)

**Comment by michal-h21** [comment]
I've posted patch with Czech and Slovak definitions for `csquotes`, so this issue should be fixed soon.

**Comment by Kyslik** [comment]
@michal-h21 great news, thanks!
