### ISSUE TITLE
Bibliography string "urlfrom" undefined

### ISSUE THREAD

**Issue by somniumAeternam** [michal-h21/biblatex-iso690#55]
I try to use the biblatex style iso-authoryear from your package and the following warning occurs:

```
Package biblatex Warning: Bibliography string 'urlfrom' undefined
(biblatex)                at entry 'baehr2010stoffbertragung' on input line 383
```

My biblatex entry is the following:
```
@book{baehr2010stoffbertragung,
	address = {Berlin, Heidelberg},
	author = {Hans Dieter Baehr and Karl Stephan},
	doi = {10.1007/978-3-642-10194-6},
	interhash = {5596b8e2b6a159ff39ec7365ad234bc9},
	intrahash = {1901d7e88f7d1cf8bbacf20f220500ec},
	isbn = {9783642055003},
	publisher = {Springer-Verlag},
	refid = {699936353},
	title = {Wärme- und Stoffübertragung},
	url = {http://www.springer.com/978-3-642-05500-3},
	x-fetchedfrom = {Bibsonomy},
	year = 2010
}
```

And my configuration in tex:

```
\usepackage{polyglossia}
\setdefaultlanguage[
	spelling=new,
	babelshorthands=true,
]{german}

\usepackage[				
	style=iso-authoryear,	
	backend=biber,	
	bibencoding=utf8,	
	autolang=other,	
	sortlocale=de_DE,	
	bibwarn=true,		
]{biblatex}
```

The final entry in the pdf is:

```
BAEHR, Hans Dieter; STEPHAN, Karl, 2010. Wärme- und Stoffübertragung. Berlin, Hei-
delberg: Springer-Verlag. ISBN 9783642055003. urlfrom DOI: 10.1007/978-3-642-
10194-6.
```

I'm using TexLive 2016 (biber 2.5) with lualatex.

**Comment by michal-h21** [comment]
It is strange, `urlfrom` language string should be declared by `Biblatex`. I don't get such warnings on your code.

**Comment by somniumAeternam** [comment]
When I declare the urlfrom in the main tex file, it is working as expected:

```
\DefineBibliographyStrings{german}{
        at = {Standort},
        bysupervisor = {Betreut von},
	urlfrom = {Verfügbar unter},
	urlalso = {Auch verfügbar unter},
}
```

I thing, that these strings are not defined in this biblatex-style.

**Comment by moewew** [comment]
The standard `german.lbx` defines `urlfrom = {{Abgerufen unter}{Abger\adddotspace unter}},`. So everything should be there. If you can give a minimal working example that we can really test (https://tex.meta.stackexchange.com/q/228/35864) we might be able to investigate this further.

**Comment by somniumAeternam** [comment]
from the official site (ftp://ftp.tug.org/tex/texlive/Contents/live/texmf-dist/tex/latex/biblatex/lbx/german.lbx):

`% urlfrom          = {{}{}},% FIXME: missing`

I have the same file. So this is the problem. It seems, it is not an issue of biblatex-iso690.

**Comment by moewew** [comment]
Mhhh, the official CTAN link for `biblatex` is: http://mirrors.ctan.org/macros/latex/contrib/biblatex/latex/lbx/german.lbx (also https://www.ctan.org/pkg/biblatex and https://github.com/plk/biblatex)
Yours seems to be what is (was) packed with some TeX live.

The string was not present in older versions of `biblatex`, but was added in version 3.5 as far as I can see. The current version is 2.7. You are running `biblatex` 3.4 (that is the version compatible to Biber 2.5)
