### ISSUE TITLE
Add option to disable dashes for consecutive editors

### ISSUE THREAD

**Issue by jnv** [michal-h21/biblatex-iso690#57]
I use iso-authoryear style. When I have consecutive entries for collection with same editors, the style generates dash with a dot instead of printing the editors' name:

![selection_2017-06-10_01](https://user-images.githubusercontent.com/616767/27004945-7c3cbe0c-4e13-11e7-8d50-9a3c18c14a5d.png)

I was able to disable this by renewing the dashcheck macro like this:

```
\renewbibmacro*{bbx:dashcheck}[2]{{#2}}
```

However, would it be possible to add option to disable this behavior, akin to standard style's `dashed` option? Or at least document this; I thought at first that this is an error in my bib database.

**Comment by DavidLuptak** [comment]
@jnv Could you also provide your bib database, please?

**Comment by DavidLuptak** [comment]
Dashcheck removed in 1e8f4fb21bd262692f8b4571d1bcec27e814549e.

**Comment by jnv** [comment]
Excellent, thank you for such a quick fix!
