### ISSUE TITLE
same name for editor and author

### ISSUE THREAD

**Issue by carepack** [michal-h21/biblatex-iso690#60]
Hi again,
and once again thx for your work. I have a little problem with @INNCOLLECTION.
If I have mulitple INNCOLLECTIONS with the same author and the author is also editor I end up with a stroke. I append an example. Look at Hellman, K.-U. Thx in advance for any help!
[output.pdf](https://github.com/michal-h21/biblatex-iso690/files/1327210/output.pdf)

and this is the content of my bib file
https://gist.github.com/carepack/e43857e078b643502a09619e3a34a591

**Comment by moewew** [comment]
Have a look at https://github.com/michal-h21/biblatex-iso690/issues/57 and https://github.com/michal-h21/biblatex-iso690/issues/58

**Comment by carepack** [comment]
thx, this fixed my problem. sorry for haven't looked by myself. I close the issue
