### ISSUE TITLE
Biblatex and keyval errors

### ISSUE THREAD

**Issue by svja87** [michal-h21/biblatex-iso690#62]
Hi !
I get 

> Package biblatex Error: Option 'urldate=edtf' invalid. }

 and 

> Package keyval Error: seconds undefined. }

in iso.bbx line 45 when I try to compile this minimal example: 

```\documentclass[a4paper, 12pt]{scrartcl}
\usepackage[ngerman]{babel}
\usepackage[babel,german=guillemets]{csquotes}
\usepackage[backend=biber,style=iso-numeric,sortlocale=de_DE,bibencoding=UTF8]{biblatex}
\addbibresource{test.bib}
\begin{document}
	test
\printbibliography
\end{document}}
```
Where is my mistake ?

**Comment by michal-h21** [comment]
Your example compile without errors for me, on recently updated TL. I've got some messages about deprecated options, one of them was about `edtf` option for `urldate`. Maybe you use a new Biblatex version not yet released to TL? I know there should be some backwards incompatible changes.

Anyway, I replaced `urldate=edtf` with `urldate=iso`, as the warning said. I also fixed the other deprecation warning. I can't recall what is the reason for the `seconds` option, but I cannot find any notice about it's deprecation.

**Comment by moewew** [comment]
I suspect you are using an ancient version of `biblatex`. Newer versions should have backwards compatibility code in place for old option names, but old versions work with the new name since they can't look into the future. The ISO/EDTF date option was initially called `iso8601`, was then renamed to `edtf` and is now called only `iso`.

**Comment by svja87** [comment]
Thank you for the help. 

> Where is my mistake ?

My fundamental mistake was to install TL from the official repositories.
Everything works fine after installing manually.
