### ISSUE TITLE
Cloned folder to ~/texmf, but TexStudio can't find the styles

### ISSUE THREAD

**Issue by tylnesh** [michal-h21/biblatex-iso690#63]
When I try to compile with the example in the README, I get:

`Package biblatex Error: Style 'iso-authoryear' not found. \RequireBibliographyStyle{\blx@bbxfile}`

**Comment by michal-h21** [comment]
Hi, you should clone the repository not directly into `~/texmf`, but to `~/texmf/tex/latex`. LaTeX looks for additional packages in this subdirectory and its children.

**Comment by tylnesh** [comment]
Thanks for the response. I did it a bit later and it still wouldn't work. Ultimately, I found out I had to install newer version of texlive, with witch it finally worked.
