### ISSUE TITLE
Inconsistent Specification of URLs

### ISSUE THREAD

**Issue by josuavogel** [michal-h21/biblatex-iso690#67]
When I add a online ressource or book and set a url, it will print: "Abgerufen unter: [url]". 
Later I declared some RFC as misc, set a url and for these it prints: "URL: [url]".

Could this be changed?

**Comment by moewew** [comment]
The URL string differs if a `urldate` is present.

https://github.com/michal-h21/biblatex-iso690/blob/c6fea4ea3bcade31bd24f73fa236bb31f1f89e47/iso.bbx#L144-L148

I don't have ISO 690 handy, bit keep in mind that `biblatex-iso690` is based on a stricter Czech translation ČSN ISO 690:2011 and not on the German translation DIN ISO 690:2013-10. I'm lead to believe there are slight differences here. The international ISO is very lax when it comes to requiring a certain style or punctuation but at least as interpreted here ČSN ISO 690 is much more strict.

You could try something like

```latex
\DeclareFieldFormat*{url}{% 
  \mainlstring{urlfrom}\addcolon\space\url{#1}}
```

**Comment by josuavogel** [comment]
Okay, I will change it for me. I know that this package adresses the Czech version, but I couldn't find a suitable german biblatex style.

**Comment by michal-h21** [comment]
Yes, we print the `urlalso` string for records which are cited as printed
material. All primarily online records should have the `urldate` field set,
because date of citation is required.

**Comment by josuavogel** [comment]
Thanks. 
So this issue can be closed.
