### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by michal-h21** [michal-h21/biblatex-iso690#69]
Maybe we should make a new release for TL 19? In order to make the distributed version compatible with current BibLaTeX.  Does anybody know about any issues we should fix before the update?

**Comment by bastianleirpo** [comment]
Old version available per Miktex is not running properly. 
Cloned and copied the repo into the package. Now it works.

**Comment by michal-h21** [comment]
I've uploaded the current code to CTAN, because an user reported that the old code here stopped to work with the current Biblatex.
