### ISSUE TITLE
Replace author with an optional organization field if empty

### ISSUE THREAD

**Issue by hendrikg8** [michal-h21/biblatex-iso690#88]
Hey, you wrote in the CTAN Package documentation, as followed:

"The persons or organizations responsible for the cited work should be primarily given in the author field. If it is not appropriate, other fields like editor and editorX family fieldsor some specific ones (e.g. translator) can be used."

In case you have an organisation like "Institute of Whatever" it will be displayed as "Whatever, Institute of" because it is sorted like Surename, Firstname. In this case there is an optinal entry called organization e.g. in the entry type Manual for example, to use to. In other packages for biblatex like \bibliographystyle{unsrtdin} it seems to me that the organisation attribute replaces the author in case it is emty.

I am not sure if it is certainly thought so, but so far I did not found any alternative for my issue. So maybe it could be intendet that way I descriebed it an should be implemented in this package as well.

I look forward to your response

**Comment by moewew** [comment]
'Corporate authors' need to be protected with curly braces to stop them from being (mis)parsed into family/given names.

```latex
  author = {{Institute of Whatever}},
```
or
```latex
  author = {{Institute of Whatever} and Anne Elk},
```
(This is true for all `biblatex` styles as well as all BibTeX styles, though some name formats may hide issues that arise if you omit the braces.) See also https://tex.stackexchange.com/q/10808/35864 and §2.3.3 *Corporate Authors and Editors*, pp. 34-35, of [the `biblatex` documentation](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf).


---

I think it should be conscious decision by the user whether or not an organisation/corporate author is placed in the author/editor/translator position or in the publisher/institution/organization position. As such I'd find it problematic to automatically move the `organization` into `author` position. But I don't know what ISO 690 has to say about that.

**Comment by hendrikg8** [comment]
Much thanks, for your tipp. That was I am looking for.
