### ISSUE TITLE
Localization does not follow the currently selected language

### ISSUE THREAD

**Issue by Witiko** [michal-h21/biblatex-iso690#90]
[BibLaTeX documentation][1] says (emphasis mine):

>  By default biblatex automatically picks up *the active surrounding language* from the babel/polyglossia package (and fall back to English if babel/polyglossia is not available).

However, the following MWE (see also [Overleaf playground][2]) shows that biblatex-iso690 follows the main language of babel (czech), not the active surrounding language (english) as evidenced by the Czech text "Dostupné z DOI" in the output:

``` tex
\documentclass{article}

\begin{filecontents}[noheader]{main.bib}
@article{tex:zpravodajchlebikova91eng,
  author = {Chlebíková, Jana},
  title = {Ako rozděliť (slovo) Československo},
  journal = {Zpravodaj CSTUG},
  volume = 1,
  number = 4,
  year = 1991,
  month = April,
  pages = 10-13,
  doi = {10.5300/1991-4/10},
}
\end{filecontents}

\usepackage[main=czech,english]{babel}
\usepackage[style=iso-numeric]{biblatex}
\addbibresource{main.bib}

\begin{document}

\selectlanguage{english}

\nocite{*}
\printbibliography

\end{document}
```

![BibLaTeX_ISO_690__Switching_languages__MWE_](https://user-images.githubusercontent.com/603082/110317910-162e5f00-800d-11eb-9530-e6782ba48df0.png)

This becomes an issue in document classes such as [csbulletin][3], where babel's main language is selected in the document class and the user can only switch the active language, not the main language. Is this an issue with biblatex-iso690, or should I take this issue upstream to [plk/biblatex][4]?

 [1]: https://mirror.kumi.systems/ctan/macros/latex/contrib/biblatex/doc/biblatex.pdf#page=49
 [2]: https://www.overleaf.com/read/hkshdtvzkyhs
 [3]: https://www.ctan.org/pkg/csbulletin
 [4]: https://github.com/plk/biblatex

**Comment by Witiko** [comment]
Looking at the source code of biblatex-iso690, I conclude that this is an issue with [plk/biblatex][1], so I am taking the issue upstream. Please, don't close the issue, so that it can be linked from the upsteam issue.

 [1]: https://github.com/plk/biblatex

**Comment by michal-h21** [comment]
Yes, we use the `\mainlang` macro provided by BibLaTeX, which switches to the main document language. I can see that this macro is deprecated, `\textmainlang` should be used instead. I expect that both of them use the main document language.

**Comment by Witiko** [comment]
@michal-h21 Perhaps we should be using just `\bibstring` instead of `\mainlangbibstring`? BibLaTeX documentation seems quite clear that the references should be localized according to the active surrounding language, not the main language.

**Comment by michal-h21** [comment]
No, some fields should be printed in the main document language according to ISO 690. So for example pages should be printed as `s.` if your document is in Czech. But other strings should be in the language of the cited document, for example journal volume. The norm is quite explicit in this, so we had to make quite some effort to support this.

**Comment by Witiko** [comment]
@michal-h21 Of course! If my document is in Czech, then I want some of the strings to be in Czech (such as "Dostupné z DOI") and some in the language of the cited document as specified by the `langid` field, there is no dispute in that.

However, the BibLaTeX documentation claims that "the language my document" should not be *the main language*, but *the currently active language*:

> By default biblatex automatically picks up *the active surrounding language* from the babel/polyglossia package (and fall back to English if babel/polyglossia is not available).

If you take a look at the MWE in the original post, then the currently active language is `english`, but the bibliography produced by biblatex-iso690 says "Dostupné z DOI" instead of "Available from DOI" as it should.

**Comment by Witiko** [comment]
@michal-h21 It seems that this is an issue that exists both in BibLaTeX and in biblatex-iso690.   
@moewew just kindly provided a patch for BibLaTeX in https://github.com/plk/biblatex/issues/1108.

**Comment by michal-h21** [comment]
The discussion continued in the main BibLaTeX tracker. @moewew posted a great comment: https://github.com/plk/biblatex/issues/1108#issuecomment-797990911

I think it would be best to provide a new package option, so user can decide if `\textmainlang` or `\textouterlang` should be used. One issue we discussed in the thread is with footnotes. Maybe it will be best to left it to the user to select the correct language for footnotes. We probably should add a section about that to the documentation.

@moewew  will be `\textouterlang` available in the BibLaTeX version shipped in TL 21?

**Comment by moewew** [comment]
> @moewew will be `\textouterlang` available in the BibLaTeX version shipped in TL 21?

I don't think so. According to http://tug.org/texlive/ the currently planned CTAN update cut-off is 22 March. A combined `biblatex`+Biber release usually takes more than a week (sometimes even two to three weeks) until all binaries are built by the volunteers. Plus we haven't really amassed a whole lot of changes, so we aren't really 'due' for another `biblatex` release on that grounds. 

I understand that this isn't ideal for `biblatex-iso690`. If you guard against `\textouterlanguage` being undefined you could already implement the option (for forward compatibility), but it would only be usable once `biblatex` v3.17 is released some time in the future.

**Comment by michal-h21** [comment]
@moewew thanks. I've added a new option, `currentlang`, which will enable the use of currently selected language. It tests for existence of `\textouterlanguage`, so it should work with the future versions of BibLaTeX. The following example works (except for footnote) with the development version:

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[main=czech,english,ngerman]{babel}
\usepackage[style=iso-numeric
  ,backref=true
  ,currentlang=true
]{biblatex}

\begin{filecontents}[force]{\jobname.bib}
@article{tex:zpravodajchlebikova91,
  author  = {Chlebíková, Jana},
  title   = {Ako rozděliť (slovo) Československo},
  journal = {Zpravodaj CSTUG},
  volume  = 1,
  number  = 4,
  year    = 1990,
  month   = {04},
  pages   = {10-13},
  doi     = {10.5300/1991-4/10},
  note    = {no laingid},
}
@article{tex:zpravodajchlebikova91cz,
  author  = {Chlebíková, Jana},
  title   = {Ako rozděliť (slovo) Československo},
  journal = {Zpravodaj CSTUG},
  volume  = 1,
  number  = 4,
  year    = 1991,
  month   = {04},
  pages   = {10-13},
  doi     = {10.5300/1991-4/10},
  langid  = {czech},
  note    = {Czech langid},
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
\nocite{*}
\printbibliography

\selectlanguage{english}
Hello\footfullcite{tex:zpravodajchlebikova91cz}
\printbibliography

\selectlanguage{ngerman}
\printbibliography
\end{document}
```

**Comment by Luk164** [comment]
Is this issue going to be fixed anytime soon? By using this package in my project I am constantly getting a warning about `\mainlang` being deprecated. Also in the meanwhile, is there a workaround I could use?

**Comment by michal-h21** [comment]
@Luk164 we use the new language selection commands, `\textmainlang` and `\textouterlang` in the development version, so we just need to release it on CTAN.

**Comment by Luk164** [comment]
@michal-h21 Great! Are there any other things that you are waiting to be finished before releasing? Just so I can keep an eye out for any progress.

**Comment by michal-h21** [comment]
I think @DavidLuptak is still working on some issues, but I think we will release a new version before TeX Live 2021 freeze, which I think will be on 22th of March.

**Comment by DavidLuptak** [comment]
- [x]  `currnetlang` package option added in 283a0962b012a8e1e11194c989f04bc2494f8d9e.
- [x]  Documentation extended in c1cb92709f8dadfbab484eb690e9d8807be081f1.

I think we can close this issue for now.

**Comment by Luk164** [comment]
@michal-h21 How is the release going? Is it gonna land today?

**Comment by michal-h21** [comment]
@Luk164 we uploaded the update to CTAN yesterday, and it was already announced as updated by CTAN.

**Comment by Luk164** [comment]
> @Luk164 we uploaded the update to CTAN yesterday, and it was already announced as updated by CTAN.

My bad, I was checking github releases

**Comment by michal-h21** [comment]
Ah, you are right. I've just made also a Github release.
