### ISSUE TITLE
Package biblatex Warning: File 'ngerman-iso.lbx' not found

### ISSUE THREAD

**Issue by MartinX3** [michal-h21/biblatex-iso690#93]
```
Package biblatex Warning: File 'ngerman-iso.lbx' not found!
(biblatex)                Ignoring mapping 'ngerman' -> 'ngerman-iso'.
```
I see, that this project only contains a `german-iso.lbx`

I wonder how I can get rid of this hopefully cosmetic warning.

I use isodate here
https://github.com/MartinX3-EducationOrganization/hbrs-latex-vorlage-praesentation/blob/a3137d24ab4c68d403de825b2bcaf830d0cc369e/aussehen/hbrs-inf.sty#L3

The n in ngerman means "Neue deutsche Rechtschreibung" our new law how to write german correct.

**Comment by michal-h21** [comment]
You can try to add the following line to your package: 

     \DeclareLanguageMapping{ngerman}{german-iso}

Does it work correctly? I don't know much about `ngerman`,  I hope we can just reuse the original German strings?

**Comment by MartinX3** [comment]
Thank you very much!
The warning is now fixed. :)

`ngerman` is the successor of `german` and specifies the splitting of words at the end of lines as far as I know.
https://www.namsu.de/Extra/pakete/German.html

**Comment by DavidLuptak** [comment]
Mapping `ngerman` directly to `german` would not use [`ngerman.lbx`](https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/ngerman.lbx) (even though there is only a single modification against [`german.lbx`](https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/german.lbx#L422) in the current upstream version of biblatex).

So I added [`ngerman-iso.lbx`](https://github.com/michal-h21/biblatex-iso690/blob/master/ngerman-iso.lbx) in d701b5766962416531f97bb0a5db7746ce322766, which would also be open to any future extensions.
